# This is a basic workflow to help you get started with Actions
name: docker-compose

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy_a
      env:
        BATION_PRIVATE_KEY: ${{ secrets.BATION_PRIVATE_KEY }}
        BATION_HOST_NAME: ${{ secrets.BATION_HOST_NAME }}
        BATION_USER_NAME: ${{ secrets.BATION_USER_NAME }}
        DEPLOY_A_PRIVATE_KEY: ${{ secrets.DEPLOY_A_PRIVATE_KEY }}
        DEPLOY_A_HOST_NAME: ${{ secrets.DEPLOY_A_HOST_NAME }}
        DEPLOY_A_USER_NAME: ${{ secrets.DEPLOY_A_USER_NAME }}
      run: |
        echo "$BATION_PRIVATE_KEY" > bation_private_key && chmod 600 bation_private_key
        ssh -o StrictHostKeyChecking=no -i bation_private_key ${BATION_USER_NAME}@${BATION_HOST_NAME} "ssh -i ~/.ssh/portfolio2.pem ${DEPLOY_A_USER_NAME}@${DEPLOY_A_HOST_NAME} 'cd ~/laravel-spa && sudo git pull origin main'"
    
