# This is a basic workflow to help you get started with Actions
name: docker-compose

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CREATE_BATION_PRIVATE_KEY
      env:
        BATION_PRIVATE_KEY: ${{ secrets.BATION_PRIVATE_KEY }}
        BATION_HOST_NAME: ${{ secrets.BATION_HOST_NAME }}
        BATION_USER_NAME: ${{ secrets.BATION_USER_NAME }}
      run: |
        echo "$BATION_PRIVATE_KEY" > bation_private_key && chmod 600 bation_private_key
    - name: Deploy_C
      env:
        DEPLOY_C_PRIVATE_KEY: ${{ secrets.DEPLOY_C_PRIVATE_KEY }}
        DEPLOY_C_HOST_NAME: ${{ secrets.DEPLOY_C_HOST_NAME }}
        DEPLOY_C_USER_NAME: ${{ secrets.DEPLOY_C_USER_NAME }}
      run: |
        echo "$DEPLOY_C_PRIVATE_KEY"
        ssh -o StrictHostKeyChecking=no -i bation_private_key ${BATION_USER_NAME}@${BATION_HOST_NAME} "echo $DEPLOY_C_PRIVATE_KEY > deploy_c_private_key && chmod 600 deploy_c_private_key"
        
